# project config for jpf-symbc extension
# only process this properties file if on top of the jpf-core model classes

jpf-symbc = ${config_path}

# we need to use ';' delimiters so that NetBeans/Ant can use this as a path spec
jpf-symbc.native_classpath=\
  ${jpf-symbc}/jpf-symbc-main/target/classes;\
  ${jpf-symbc}/jpf-symbc-annotations/target/classes;\
  ${jpf-symbc}/jpf-symbc-classes/target/classes;\
  ${jpf-symbc}/repo/com/microsoft/z3/4.8.14/z3-4.8.14.jar;\
  ${jpf-symbc}/repo/choco/choco/1.2.04/choco-1.2.04.jar;\
  ${jpf-symbc}/repo/choco/choco-solver/2.1.1/choco-solver-2.1.1.jar;\
  ${jpf-symbc}/repo/com/ufpe/coral/0.7/coral-0.7.jar;\
  ${jpf-symbc}/repo/org/opt4j/opt4j/2.4/opt4j-2.4.jar;\
  ${jpf-symbc}/repo/za/ac/sun/green/1.0/green-1.0.jar;\
  ${jpf-symbc}/repo/edu/stanford/hampi/1.0/hampi-1.0.jar;\
  ${jpf-symbc}/repo/com/iastate/iasolver/1.0/iasolver-1.0.jar;\
  ${jpf-symbc}/repo/edu/nyu/libcvc3/2.3.0/libcvc3-2.3.0.jar;\
  ${jpf-symbc}/repo/edu/nyu/libcvc3/5.0.0/libcvc3-5.0.0.jar;\
  ${jpf-symbc}/repo/org/sat4j/org.sat4j.core/CUSTOM-20100705/org.sat4j.core-CUSTOM-20100705.jar;\
  ${jpf-symbc}/repo/org/sat4j/org.sat4j.pb/CUSTOM-20100705/org.sat4j.pb-CUSTOM-20100705.jar;\
  ${jpf-symbc}/repo/edu/ucsb/scale/1.0/scale-1.0.jar;\
  ${jpf-symbc}/repo/edu/ucsb/solver/1.0/solver-1.0.jar;\
  ${jpf-symbc}/repo/edu/ucsb/string/1.0/string-1.0.jar;\
  ${jpf-symbc}/repo/edu/ucsb/proteus/1.0/proteus-1.0.jar;\
  ${jpf-symbc}/repo/edu/ucsb/statemachines/1.0/statemachines-1.0.jar;\
  ${jpf-symbc}/repo/org/stp/stpjni/1.0/stpjni-1.0.jar;\
  ${jpf-symbc}/repo/edu/sri/yicesapijava/1.0/yicesapijava-1.0.jar;\
  ${jpf-symbc}/repo/att/research/grappa/1.0/grappa-1.0.jar

jpf-symbc.Linux.amd64.native_libraries=\
  /usr/local/lib/libabc.so;\
  ${jpf-symbc}/lib/libz3java.so;\
  ${jpf-symbc}/lib/64bit/libz3.so;\
  ${jpf-symbc}/lib/64bit/libcvc3jni.so;

jpf-symbc.Windows.amd64.native_libraries=\
  ${jpf-symbc}/lib/libz3java.dll;\
  ${jpf-symbc}/lib/libz3.dll;

jpf-symbc.classpath=\
  ${jpf-symbc}/jpf-symbc-classes/target/classes;\
  ${jpf-symbc}/jpf-symbc-annotations/target/classes

jpf-symbc.test_classpath=\
  ${jpf-symbc}/jpf-symbc-tests/target/test-classes


### configurations specific to the symbc project

jpf-symbc.peer_packages = gov.nasa.jpf.symbc

jvm.insn_factory.class=gov.nasa.jpf.symbc.SymbolicInstructionFactory

# no state matching
vm.storage.class=nil

# strings configuration
strings.z3str=/home/miroslav/Research/jpf/Z3-str/Z3-str.py
strings.do_versioning=no

strings.temp_file=./temp.z3str
strings.interactive_flags=-f ${strings.temp_file}
strings.save_temp_file_after_run=no
